export const MEDIA_FIELDS = {
  Movie: [
    "title",
    "genre",
    "tag",
    "tag_full",
    "collection",
    "plot",
    "studio",
    "actor",
    "director",
    "writer",
    "library_name",
    "content_rating",
    "language",
    "language_tag",
    "sub_language",
    "sub_language_tag",
    "release_date",
    "added_date",
    "chapters",
    "minutes",
    "seconds",
    "height",
    "width",
    "video_codec",
    "video_bit_depth",
    "video_dynamic_range",
    "type",
  ],
  Show: [
    "title",
    "genre",
    "tag",
    "tag_full",
    "collection",
    "plot",
    "studio",
    "network",
    "actor",
    "library_name",
    "content_rating",
    "language",
    "language_tag",
    "sub_language",
    "sub_language_tag",
    "release_date",
    "added_date",
    "type",
  ],
  Season: [
    "title",
    "tag",
    "tag_full",
    "collection",
    "library_name",
    "season_number",
    "language",
    "language_tag",
    "sub_language",
    "sub_language_tag",
    "show_title",
    "show_genre",
    "show_studio",
    "show_content_rating",
    "show_tag",
    "type",
  ],
  Episode: [
    "title",
    "plot",
    "director",
    "writer",
    "tag",
    "tag_full",
    "collection",
    "library_name",
    "language",
    "language_tag",
    "sub_language",
    "sub_language_tag",
    "release_date",
    "added_date",
    "chapters",
    "minutes",
    "seconds",
    "height",
    "width",
    "season_number",
    "episode_number",
    "show_title",
    "show_genre",
    "show_studio",
    "show_network",
    "show_content_rating",
    "show_tag",
    "video_codec",
    "video_bit_depth",
    "video_dynamic_range",
    "type",
  ],
  Artist: [
    "title",
    "genre",
    "style",
    "mood",
    "language",
    "language_tag",
    "sub_language",
    "sub_language_tag",
    "collection",
    "added_date",
    "library_name",
    "type",
  ],
  "Music Video": [
    "title",
    "artist",
    "album",
    "genre",
    "tag",
    "tag_full",
    "collection",
    "library_name",
    "language",
    "language_tag",
    "sub_language",
    "sub_language_tag",
    "release_date",
    "added_date",
    "chapters",
    "minutes",
    "seconds",
    "height",
    "width",
    "video_codec",
    "video_bit_depth",
    "video_dynamic_range",
    "type",
  ],
  "Other Video": [
    "title",
    "genre",
    "tag",
    "tag_full",
    "collection",
    "plot",
    "studio",
    "actor",
    "director",
    "writer",
    "library_name",
    "content_rating",
    "language",
    "language_tag",
    "sub_language",
    "sub_language_tag",
    "release_date",
    "added_date",
    "chapters",
    "minutes",
    "seconds",
    "height",
    "width",
    "video_codec",
    "video_bit_depth",
    "video_dynamic_range",
    "type",
  ],
  Song: [
    "title",
    "album",
    "artist",
    "album_artist",
    "genre",
    "tag",
    "tag_full",
    "collection",
    "library_name",
    "minutes",
    "seconds",
    "added_date",
    "type",
  ],
  Image: [
    "title",
    "genre",
    "tag",
    "tag_full",
    "collection",
    "library_name",
    "added_date",
    "type",
  ],
};

export const SPECIAL_FIELDS = {
  released_inthelast: "Released in the last X (days/weeks/months/years)",
  released_notinthelast: "Not released in the last X (days/weeks/months/years)",
  released_onthisday: "Released on this day (X years)",
  added_inthelast: "Added in the last X (days/weeks/months/years)",
  added_notinthelast: "Not added in the last X (days/weeks/months/years)",
};

export const UNITS = ["days", "weeks", "months", "years"];

export const OPERATORS = ["=", "contains", "starts with", "ends with", "range"];

export const TYPE_VALUES = [
  "movie",
  "show",
  "season",
  "episode",
  "artist",
  "music_video",
  "other_video",
  "song",
  "image",
];
